# Configuraci�n de puerto y nombre de aplicaci�n
server.port=8080
spring.application.name=GameVault

# ==========================================
# CONFIGURACI�N DE BASE DE DATOS (MySQL)
# ==========================================
# Aseg�rate de tener una base de datos creada llamada 'gamevaultdb' en MySQL Workbench
# TIP: Al agregar '?createDatabaseIfNotExist=true' al final de la URL, MySQL la crear� por ti autom�ticamente si no existe.
spring.datasource.url=jdbc:mysql://localhost:3306/gamevaultdb?serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=itson
# update: Crea las tablas si no existen o las actualiza, pero no las borra.
spring.jpa.hibernate.ddl-auto=update
# Muestra las consultas SQL en la consola para fines did�cticos
spring.jpa.show-sql=true